config/routes.rb
Rails.application.routes.draw do
  resources :scrappers
  devise_for :users
  root to: "scrappers#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :scrapper
end

app/models/scrapper.rb
class Scrapper < ActiveRecord::Base
  belongs_to :user
  has_many :products, dependent: :delete_all
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :scrappers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scrappers_controller.rb
require 'metainspector'
require 'nokogiri'
require 'open-uri'

class ScrappersController < ApplicationController
  before_action :set_scrapper, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /scrappers
  # GET /scrappers.json
  def index
    @scrappers = current_user.scrappers
  end

  # GET /scrappers/1
  # GET /scrappers/1.json
  def show
    url = @scrapper.url
    @metatags = MetaInspector.new(url)
    @doc = @scrapper.products
  end

  # GET /scrappers/new
  def new
    @scrapper = Scrapper.new
  end

  # GET /scrappers/1/edit
  def edit
  end

  # POST /scrappers
  # POST /scrappers.json
  def create
    url = params[:scrapper][:url]
    @scrapper = Scrapper.new(user_id: current_user.id, url: url)
    # checking if scrapper is saved or not. This is to make sure we dont have crappy data in db.
    is_scrapper_saved = @scrapper.save
    # create products for scrapper only if it is valied and saved in db.
    if is_scrapper_saved
      doc = Nokogiri::HTML(open(url))
      items = doc.css(".s-item-container")
      items.each do |item|
       Product.create!(
        title: item.css(".s-access-title").text.strip,
        price: item.css(".s-price").text.split(',').map!(&:strip).join().gsub(/\p{Space}/,'').to_d,
        rating: item.css("span+ .a-text-normal").text.to_f,
        cod: item.css(".a-spacing-top-mini").text,
        scrapper_id: @scrapper.id,
        user_id: current_user.id)
      end
    end
    respond_to do |format|
      if is_scrapper_saved
        format.html { redirect_to scrappers_path, notice: 'Scrapper was successfully created.' }
        format.json { render :show, status: :created, location: @scrapper }
      else
        format.html { render :new }
        format.json { render json: @scrapper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scrappers/1
  # PATCH/PUT /scrappers/1.json
  def update
    respond_to do |format|
      if @scrapper.update(scrapper_params)
        format.html { redirect_to @scrapper, notice: 'Scrapper was successfully updated.' }
        format.json { render :show, status: :ok, location: @scrapper }
      else
        format.html { render :edit }
        format.json { render json: @scrapper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scrappers/1
  # DELETE /scrappers/1.json
  def destroy
    @scrapper.destroy
    respond_to do |format|
      format.html { redirect_to scrappers_url, notice: 'Scrapper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scrapper
      @scrapper = Scrapper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scrapper_params
      params.require(:scrapper).permit(:user_id, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scrappers_helper.rb
module ScrappersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Scrape Amazon", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path %></li>

        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
      <ul>
          <li><%= link_to "Create New Scraper", new_scrapper_path, class: "navbar-form navbar-right" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PmCloud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div> 

</body>
</html>

app/views/scrappers/_form.html.erb
<%= form_for(@scrapper) do |f| %>
  <% if @scrapper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scrapper.errors.count, "error") %> prohibited this scrapper from being saved:</h2>

      <ul>
      <% @scrapper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scrappers/edit.html.erb
<h1>Editing Scrapper</h1>

<%= render 'form' %>

<%= link_to 'Show', @scrapper %> |
<%= link_to 'Back', scrappers_path %>

app/views/scrappers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scrappers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scrappers.each do |scrapper| %>
      <tr>
        <td><%= scrapper.url %></td>
        <td><%= link_to 'Show', scrapper %></td>
        <td><%= link_to 'Edit', edit_scrapper_path(scrapper) %></td>
        <td><%= link_to 'Destroy', scrapper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<br>

<%= link_to 'New Scrapper', new_scrapper_path %>

app/views/scrappers/new.html.erb
<h1>New Scrapper</h1>

<%= render 'form' %>

<%= link_to 'Back', scrappers_path %>

app/views/scrappers/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Scraped Data</h1>

<dl class="dl-horizontal">
	<dt>Url: </dt>
	<dd><%= @scrapper.url %></dd>
	<dt>Title: </dt>
	<dd><%= @metatags.title%></dd>
	<dt> Meta Tag Description:</dt>
	<dd><%= @metatags.meta_tags["name"]["description"].first %></dd>
	<dt> Meta Tag Keywords:</dt>
	<dd><%= @metatags.meta_tags["name"]["keywords"].first %></dd>
</dl>

<%= link_to 'Edit', edit_scrapper_path(@scrapper) %> |
<%= link_to 'Back', scrappers_path %>

<table class="table table-hover">
   <thead>
     <tr class="success">
       <th>Product Name</th>
       <th>Price</th>
       <th>Rating</th>
       <th>COD</th>
     </tr>
   </thead>

   <tbody>
     <% @doc.each do |item| %>
       <tr class ="info">
         <td><%= item.title %></td>
         <td><%= item.price.to_s %></td>
         <td><%= item.rating %></td>
         <td><%= item.cod %></td>
       </tr>
    <% end %>
   </tbody>
</table>